# -*- coding: utf-8 -*-
"""MentorTasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKkzoF-dEoTfHtTmm6Co3vPIoFgJTE8g

# **First Task: The Cafe Receipt Generator**
"""

print("Welcome to the Python Roasters POS System!")
print("------------------------------------------")

customer_name = input("Enter customer name: ")
item_name = input("Enter the item name: ")

price = float(input("Enter item price: "))
quantity = int(input("Enter quantity: "))

total_cost = price * quantity

print()
print("Generating Receipt...")
print("==========================================")
print("CUSTOMER:", customer_name)
print("ITEM:", item_name)
print("QUANTITY:", quantity)
print("PRICE PER ITEM:", price)
print("------------------------------------------")
print("TOTAL AMOUNT DUE:", total_cost)
print("==========================================")
print("Thank you for visiting!")

